
PLAY [Run BACKUP to TFTP (Switches)] *******************************************

TASK [make "file prompt quiet"] ************************************************
ok: [192.168.250.9]
ok: [192.168.250.6]
ok: [192.168.250.8]
ok: [192.168.250.98]
ok: [192.168.250.7]
ok: [192.168.250.13]
ok: [192.168.250.85]
ok: [192.168.250.82]

TASK [copy run to tftp] ********************************************************
ok: [192.168.250.9]
ok: [192.168.250.6]
ok: [192.168.250.7]

TASK [make "file prompt quiet"] ************************************************
ok: [192.168.202.17]
ok: [192.168.203.17]

TASK [copy run to tftp] ********************************************************
ok: [192.168.250.8]
ok: [192.168.250.98]
ok: [192.168.250.13]
ok: [192.168.250.85]
ok: [192.168.203.17]
ok: [192.168.202.17]
fatal: [192.168.250.82]: FAILED! => {"changed": false, "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."}

PLAY [Run BACKUP to TFTP (ASA)] ************************************************

TASK [backup to tftp] **********************************************************
ok: [192.168.201.18]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: timed out
fatal: [192.168.201.10]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/alex/.ansible/tmp/ansible-local-260346wcp12yab/ansible-tmp-1652100373.6171262-261387-151100600659903/AnsiballZ_asa_command.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/alex/.ansible/tmp/ansible-local-260346wcp12yab/ansible-tmp-1652100373.6171262-261387-151100600659903/AnsiballZ_asa_command.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/alex/.ansible/tmp/ansible-local-260346wcp12yab/ansible-tmp-1652100373.6171262-261387-151100600659903/AnsiballZ_asa_command.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.asa.asa_command', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_asa_command_payload_g0anwbn9/ansible_asa_command_payload.zip/ansible/modules/network/asa/asa_command.py\", line 186, in <module>\n  File \"/tmp/ansible_asa_command_payload_g0anwbn9/ansible_asa_command_payload.zip/ansible/modules/network/asa/asa_command.py\", line 156, in main\n  File \"/tmp/ansible_asa_command_payload_g0anwbn9/ansible_asa_command_payload.zip/ansible/module_utils/network/asa/asa.py\", line 125, in run_commands\n  File \"/tmp/ansible_asa_command_payload_g0anwbn9/ansible_asa_command_payload.zip/ansible/module_utils/connection.py\", line 190, in __rpc__\nansible.module_utils.connection.ConnectionError: timed out\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
192.168.201.10             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
192.168.201.18             : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.202.17             : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.203.17             : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.250.13             : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.250.6              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.250.7              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.250.8              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.250.82             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
192.168.250.85             : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.250.9              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.250.98             : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

